model_name : classifier
data_version: eA_w10_c20_64_64
convolution_method: 3D_seq

mlflow_parameters:
  tracking_uri: http://127.0.0.1:5000
  experiment_name: Seizure Detection


data_parameters:
  seed: 0
  data_fraction: 0.2
  split_proportions: [0.8, 0.1, 0.1]

  # Dataloaders parameters
  batch_size: 64
  num_workers: 0
  pin_memory: True
  
  # Augmentation
  shuffle_prob: 1
  invert_prob: 0.1

# Training hyperparameters
model_parameters:
  device: cuda
  in_channels: 1
  num_classes: 2
  dropout: 0.1

  num_epochs: 3

  # optimizer: SGD
  # learning_rate: 0.0001
  # momentum: 0.5
  # weight_decay: 0.000001

  optimizer: Adam
  learning_rate: 0.0001
  weight_decay: 0.0001

  # lr_scheduler: cosine  
  # t_max: 30
  # eta_min: 0.00001

  lr_scheduler: step
  step_size: 100
  gamma: 1

  # Parameters for stoppers
  init_stopper_patience: 5
  early_stopper_patience: 10
  early_stopper_min_delta: 1

  # eval "$(ssh-agent -s)"
  # ssh-add ~/.ssh/405_work_key