data_version: eA_w03_c03_64_64
model_name : classifier

mlflow_parameters:
  tracking_uri: http://127.0.0.1:5000
  experiment_name: Seizure Detection


data_parameters:
  seed: 0
  data_fraction: 1
  split_proportions: [0.7, 0.2, 0.1]

  # Dataloaders parameters
  batch_size: 128
  num_workers: 0
  pin_memory: True
  
  # Augmentation


# Training hyperparameters
model_parameters:
  device: cuda
  in_channels: 1
  num_classes: 2
  dropout: 0.1

  num_epochs: 100

  # Hyperparameters for SGD
  learning_rate: 0.003
  weight_decay: 0.000001

  # lr_scheduler: cosine  
  # t_max: 30
  # eta_min: 0.00001

  lr_scheduler: step
  step_size: 20
  gamma: 0.3

  # Parameters for stoppers
  init_stopper_patience: 5
  early_stopper_patience: 10
  early_stopper_min_delta: 1